### ISSUE TITLE
Exception: Items are not unique

### ISSUE THREAD

**Issue by ssda-developer** [ram6ler/dart-trotter#1]
Hi, if I use a String where characters are repeated, for example, "2842" then I get an error: 
[Exception: Items are not unique](https://user-images.githubusercontent.com/26069368/83866073-e7a6ef00-a72f-11ea-858a-063a4ab6b56c.png)
Is this normal behavior or can it be fixed?

**Comment by ram6ler** [comment]
Hi,

Yes - this is normal behavior. The combinatorics structures assume unique items.

For non unique items, you can simply work with the indices (which are necessarily unique) and then map the indices to the respective items, but some structures will, of course, be repeated.

For more information, take a look at [this stackoverflow question and answer](https://stackoverflow.com/questions/57831836/is-it-possible-to-get-permutations-for-a-string-that-has-repeated-characters). 

Hope that helps!
