### ISSUE TITLE
Cannot run with sound null safety, because the following dependencies don't support null safety

### ISSUE THREAD

**Issue by Alireza01** [ram6ler/dart-trotter#2]
i get this error after importing your library:
"Cannot run with sound null safety, because the following dependencies don't support null safety"

**Comment by ram6ler** [comment]
Thanks for your interest in this library.

I can't reproduce this issue. Could you check which version of trotter you're using?

**Comment by Alireza01** [comment]
i am using the latest 1.2.0

**Comment by ram6ler** [comment]
Got it — I introduced null safety as a pre-release and then never updated the "latest". It's updated now; please use version 2.0.0. Thanks for bringing this to my attention.
